# Generated by Django 5.0.6 on 2024-10-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UIDmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('phno', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('UID', models.CharField(blank=True, max_length=7, unique=True)),
                ('password', models.CharField(default='Welcome', max_length=5)),
            ],
        ),
    ]
